---
title: "Wildlife Management and Invasive Species (INBO)"
author: 
    name: "Contact information"
    email: "faunabeheer@inbo.be"
subtitle: "This homepage provides an overview of all interactive web versions of reports made by the Wildlife Management and Invasive Species group at the Research Institute for Nature and Forest (INBO, Flanders, Belgium)."
reportnr: ""
ordernr: ""
link-citations: TRUE
css: "css/inbo_rapport.css"
output:
  html_document:
    self_contained: FALSE
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(rgdal)
library(inborutils)
library(kableExtra)
#library(mapview)
#library(raster)
library(knitr)
opts_chunk$set(
  echo = FALSE, 
  eval = TRUE,
  cache = FALSE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  warning = TRUE,
  error = TRUE,
  message = TRUE
)
library(INBOtheme)
theme_set(
  theme_inbo(
    base_family = "Calibri", # "Flanders Art Sans",
    base_size = 12
  )
)
if (!interactive() && opts_knit$get("rmarkdown.pandoc.to") != "html") {
  opts_chunk$set(dev = "cairo_pdf")
  theme_set(
    theme_inbo(
      base_family = "Calibri", # "Flanders Art Sans",
      base_size = 8
    )
  )
}
```

# {-}

\benglish

Welcome to the reports homepage of the Wildlife Management and Invasive Species group at INBO.
Although this page is still under construction, the reports embedded are all finished.
Our current (limited) list of interactive reports is:
  
```{r filenames, include=FALSE}
fileNames <- Sys.glob(file.path("../Reports","*"))
```

```{r list, echo=FALSE, results='asis'}
for (i in fileNames){
  j <- gsub("../Reports/","",i)
  cat("[",j,"](//inbo.github.io/fis-reports/Reports/",j,"/index.html)", sep="")
  cat(fill=TRUE)
  cat("\n")
}
```

Enjoy reading!
  
\eenglish

\mainmatter


