---
title: "Wildlife Management and Invasive Species (INBO)"
author: 
    name: "Contact information"
    email: "faunabeheer@inbo.be"
subtitle: "This homepage provides an overview of all interactive web versions of reports made by the Wildlife Management and Invasive Species group at the Research Institute for Nature and Forest (INBO, Flanders, Belgium)."
reportnr: ""
ordernr: ""
link-citations: TRUE
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    split_by: "chapter+number"
    template: !expr INBOmd::inbo_rapport_css("html")
  bookdown::pdf_book:
    base_format: INBOmd::inbo_rapport
  bookdown::epub_book:
    stylesheet: "css/inbo_rapport.css"
    template: !expr INBOmd::inbo_rapport_css("epub")
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(rgdal)
library(inborutils)
library(kableExtra)
#library(mapview)
#library(raster)
library(knitr)
opts_chunk$set(
  echo = FALSE, 
  eval = TRUE,
  cache = FALSE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  warning = TRUE,
  error = TRUE,
  message = TRUE
)
library(INBOtheme)
theme_set(
  theme_inbo(
    base_family = "Calibri", # "Flanders Art Sans",
    base_size = 12
  )
)
if (!interactive() && opts_knit$get("rmarkdown.pandoc.to") != "html") {
  opts_chunk$set(dev = "cairo_pdf")
  theme_set(
    theme_inbo(
      base_family = "Calibri", # "Flanders Art Sans",
      base_size = 8
    )
  )
}
```

# {-}

\benglish

Welcome to our interactive reports homepage, which, clearly, is still under construction.
The reports embedded are however all finished.
Our current list of interactive reports is:
  
```{r filenames, include=FALSE}
fileNames <- Sys.glob(file.path("../Reports","*"))
```

```{r list, echo=FALSE, results='asis'}
for (i in fileNames){
  j <- gsub("../Reports/","",i)
  cat("[",j,"](//inbo.github.io/fis-reports/",i,"/index.html)", sep="")
  cat(fill=TRUE)
  cat("\n")
}
```

Enjoy reading!
  
\eenglish

\mainmatter


